e-dialect/hinghwa-dict-web

src/components/Tools/RelativeSelect.vue
src/views/Tools/Tools.vue

feat: relative icon and bottom

---

src/components/Tools/PinyinList.vue
src/components/Tools/RelativeSelect.vue
src/views/Login/Login.vue
src/views/Tools/Tools.vue

docs: change bracket to full width

---

src/components/Articles/CommentList.vue

fix: can't comment without login

---

src/consts/urls.js
src/services/words.js
src/utils/request.js
src/views/Words/WordDetails.vue

refactor: use request.js and services

---

src/views/Users/Notification.vue

close #40
https://user-images.githubusercontent.com/106299221/202427896-8452c819-3abe-4854-9caa-cdcccba235a5.mp4

fix: fix all select button

---

src/components/HeaderAndFooter/Footer.vue
src/components/Tools/SelectSearch.vue
src/views/Articles/ArticleDetails.vue
src/views/Home.vue
src/views/Pinyin.vue

close #33 
close #43
https://user-images.githubusercontent.com/106299221/199920516-2b72ff8b-a6af-478b-a4fc-48c00c4d18de.mp4

feat: add searching by selection

---

src/views/Users/UserSettings.vue

fix: add login in settings

---

src/services/quiz.js
src/views/Quiz/Quiz.vue
src/views/Quiz/QuizDetails.vue
src/views/Quiz/QuizResearch.vue
src/views/Users/UserSettings.vue

refactor: refactor quiz

---

src/components/Admin/Record.vue

feat: add text attention for review

---

src/components/Admin/Record.vue

close #41 
https://user-images.githubusercontent.com/106299221/211188831-b36a0351-42f3-4d79-83a4-c14c54a1535e.mp4

feat: add filter about recordStatus

---

src/components/HeaderAndFooter/Footer.vue
src/views/Home.vue

feat: add tuxiaochao

---

src/components/Admin/Record.vue
src/views/Quiz/QuizDetails.vue

close #56 
audio我写了v-if=‘quiz.voice_source’，我在测试的时候没有随机到已经录好语音的，所以就先把v-if给删了，截了上面的图给学长先看看效果
那个黄色的是一个悬浮提示框，鼠标放在语音框上才会显示

feat: add quiz voice

---

src/App.vue
src/services/login.js

fix: refresh token on site created

---

src/views/Words/Application.vue

close #52 
测试过程：
1、创建一个新词条
2、在审核界面增加该词条的内容（每个字段都有尝试）
3、审核通过（即创建词条）
4、搜索该词条，发现管理员新增加的内容有保留

fix: fix create word

---

src/router/index.js
src/services/dictionary.js
src/views/Dictionary/Dictionary.vue
src/views/Home.vue

feat: preparation for dictionary

---

src/components/Pronunciation/RankList.vue
src/router/index.js
src/views/Tools/QuickRecording.vue

close #55 
（不过现在还有点奇怪 emm我是传递了7、30、0，可是现在周榜，月榜和总榜是一样的，也没有出现报错）

feat(recordRank): add recordRank

---

src/App.vue
src/views/Home.vue
src/views/Tools/Tools.vue

去除网页入口的强制缩放

---

src/views/Home.vue

close #91 
fix(home): change alert from warning to info

更改首页上方的 alert 为 info

---

src/components/Pronunciation/RankList.vue
src/views/Home.vue

close #90 
fix(home): change font-size and color

调整首页文字大小和颜色

---

src/App.vue
src/components/Pronunciation/RankList.vue
src/views/Home.vue
src/views/Tools/Tools.vue

refactor: remove resize in the site
（这个作为整个合并操作的入口，如果后续发现问题会一直往这上面提交，开这个页面也是为了看效果）

去除网页入口强制缩放

---

src/components/Admin/Record.vue

close #94 
fix(record): change the way of record filter

依据字段对录音审核进行筛选

---

src/services/login.js
src/services/website.js
src/store/index.js
src/views/Users/Notification.vue

fix(user): fix for notifications APIs changing
close #100

修复通知模块（后端 API 变动）

---

src/components/Admin/Record.vue
src/components/Pronunciation/RankList.vue

close #109
分页器问题确实我也发现了，但是我改了比较久还是没改出来orz，先提交修复了’录音审核后仍保持原过滤状态‘这个问题的代码吧

录音审核后仍保持原过滤状态

---

src/views/Words/Application.vue

fix(wordApplication): get this.application.word
close #103

删除管理员字词审核的冗余提交

---

src/views/Quiz/QuizDetails.vue
src/views/Quiz/QuizResearch.vue

fix(Quiz): fix Quiz route
close #112

修复聪明花开随机测试题和搜索测试题的路由

---

src/views/Words/WordDetails.vue

close #116 
fix(wordDetail-record): change how to read country and town

修复词语详情页录音的城乡数据读取

---

src/views/Words/WordList/WordList.vue
src/views/Words/WordList/WordListDetail.vue

refactor(wordlist): format date

---

src/App.vue
src/components/Word/WordList/MultiWordsMode.vue
src/components/Word/WordList/SingleWordMode.vue
src/router/pc2mob.json
src/views/Words/WordList/WordList.vue
src/views/Words/WordList/WordListDetail.vue

feat: add jumper from pc to mobile

---

src/components/Articles/CommentList.vue

fix(comment): remove unexpected space at comment region

---

src/views/Words/Application.vue

fix(confirming): remove 'undefined' result when confirming

---

src/components/User/Notifications/EmailViewer.vue

feat(notification): support TypeLinks

---

package.json
src/components/User/CertificatePane.vue
src/router/index.js
src/views/Home.vue
src/views/Users/Certificate.vue
src/views/Users/UserDetails.vue
yarn.lock

fix(certificate): add certificate system

fix(certificate): add certificate system

---

src/components/Admin/Record.vue

fix(record): fix HTTP method of the pronunciation verification

---

package.json
yarn.lock

fix compatibility with node 22

build: bump @achrinza/node-ipc
